# Generated by Django 6.1 on 2026-08-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('mac_address', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(db_index=True, max_length=200)),
                ('interface', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Capturing'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('tcp_count', models.PositiveIntegerField(default=0)),
                ('udp_count', models.PositiveIntegerField(default=0)),
                ('icmp_count', models.PositiveIntegerField(default=0)),
                ('dns_count', models.PositiveIntegerField(default=0)),
                ('arp_count', models.PositiveIntegerField(default=0)),
                ('ipv4_count', models.PositiveIntegerField(default=0)),
                ('ipv6_count', models.PositiveIntegerField(default=0)),
                ('requested_packet_count', models.PositiveIntegerField(default=0, help_text='0 means capture until stopped.')),
                ('protocol_filter', models.CharField(blank=True, default='', help_text='Optional filter label.', max_length=16)),
                ('payload_storage_enabled', models.BooleanField(default=False, help_text='Whether payload previews were stored for this session.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='sniffer_cap_status_c5196a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source_ip', models.CharField(blank=True, db_index=True, default='', max_length=45)),
                ('destination_ip', models.CharField(blank=True, db_index=True, default='', max_length=45)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('transport_protocol', models.CharField(blank=True, default='', max_length=16)),
                ('packet_length', models.PositiveIntegerField(default=0)),
                ('ttl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tcp_flags', models.CharField(blank=True, default='', max_length=16)),
                ('icmp_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('icmp_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload_length', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_preview', models.TextField(blank=True, default='')),
                ('payload_hex', models.TextField(blank=True, default='')),
                ('is_ipv4', models.BooleanField(default=False)),
                ('is_ipv6', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='sniffer.capturesession')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DNSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(db_index=True, max_length=255)),
                ('query_type', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('response_code', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_queries', to='sniffer.packet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['session', 'timestamp'], name='sniffer_pac_session_d954ec_idx'),
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['session', 'protocol'], name='sniffer_pac_session_a6c15e_idx'),
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['protocol', 'timestamp'], name='sniffer_pac_protoco_e47666_idx'),
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['source_ip', 'destination_ip'], name='sniffer_pac_source__6594e9_idx'),
        ),
        migrations.AddIndex(
            model_name='packet',
            index=models.Index(fields=['session', 'source_port', 'destination_port'], name='sniffer_pac_session_479774_idx'),
        ),
        migrations.AddIndex(
            model_name='dnsquery',
            index=models.Index(fields=['query_name', 'query_type'], name='sniffer_dns_query_n_410bd2_idx'),
        ),
    ]
