# Generated by Django 6.1 on 2026-08-14 21:00

import django.utils.timezone
from django.db import migrations, models


def backfill_heartbeat_from_start(apps, schema_editor):
    CaptureSession = apps.get_model("sniffer", "CaptureSession")
    CaptureSession.objects.update(last_heartbeat=models.F("started_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='last_heartbeat',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_heartbeat_from_start, migrations.RunPython.noop),
    ]
